services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: 0.22.26
        TARGETARCH: arm64
    image: pocketbase:0.22.26
    container_name: pocketbase-dev
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - ADMIN_EMAIL=your-custom-email@example.com
      - ADMIN_PASSWORD=your-custom-password
